version: '3.3'

services:
  booking-service:
    image: booking-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8090"
    networks:
      - booking-service-network

  booking-service-database:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Your_new_password1
      MYSQL_DATABASE: booking_service-hotel
      MYSQL_USER: databaseUser
      MYSQL_PASSWORD: password1
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      - booking-service-network
      
  rabbitmq-broker:
    image: dominikhastrich/rabbitmq-web-stomp
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674    
      - 62623:62623
      - 61613:61613
    networks:
      - booking-service-network 
      
volumes:
  mysql:
      
networks:
  booking-service-network:
  
  # docker pull dominikhastrich/rabbitmq-web-stomp
  # itzg/rabbitmq-stomp
